/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "nsIBaseWindow.idl"

[scriptable, uuid(2d641949-5f4b-426f-b969-37779a976ea3)]

interface nsIHTitleWindow : nsISupports {
    long setHideTitlebarWhenMaximized(in nsIBaseWindow aWindow);
};
